/** Prescription as returned by the API — optical powers are integer × 100. */
export type PrescriptionRecord = {
  id: number;
  rxNumber: string;
  patientId: number;
  doctorName: string;
  rxDate: string;
  rxTime?: string;
  chiefComplaint?: string | null;
  vaReUnaided?: string | null;
  vaLeUnaided?: string | null;
  vaReAided?: string | null;
  vaLeAided?: string | null;
  dvReSph: number;
  dvReCyl: number;
  dvReAxis: number | null;
  dvReAdd: number;
  dvReVa: string | null;
  dvLeSph: number;
  dvLeCyl: number;
  dvLeAxis: number | null;
  dvLeAdd: number;
  dvLeVa: string | null;
  nvReSph: number;
  nvReCyl: number;
  nvReAxis: number | null;
  nvReAdd: number;
  nvReVa: string | null;
  nvLeSph: number;
  nvLeCyl: number;
  nvLeAxis: number | null;
  nvLeAdd: number;
  nvLeVa: string | null;
  pdType: string;
  pdBinocular: number | null;
  pdRe: number | null;
  pdLe: number | null;
  prismRePower?: number | null;
  prismReBase?: string | null;
  prismLePower?: number | null;
  prismLeBase?: string | null;
  lensType: string;
  frameType: string | null;
  tint?: string | null;
  coating?: string[] | null;
  doctorNotes: string | null;
  nextVisitDate: string | null;
  followupReason?: string | null;
};
